# Proyecto #1 - Ciencia de Datos en Python

### Importación de Librerias

In [30]:
# Se importan las librerias que se utilizan en el proyecto
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Separación de Datos en 2 Datasets

In [11]:
# Se cargan los datos para ser separados posteriormente
df = np.load("data/proyecto_training_data.npy")
print(df.shape)
print(df)

(1460, 6)
[[2.08500e+05 7.00000e+00 8.56000e+02 8.00000e+00 2.00300e+03 6.50000e+01]
 [1.81500e+05 6.00000e+00 1.26200e+03 6.00000e+00 1.97600e+03 8.00000e+01]
 [2.23500e+05 7.00000e+00 9.20000e+02 6.00000e+00 2.00100e+03 6.80000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]


In [13]:
# Se calcula el indice en el que se va partir la data para la validación y pruebas
idx_split = int(df.shape[0] * 0.8)

# Dataset de validacion y pruebas
val_set = df[idx_split:, :] # Se toman los valores a partir del índice (sin incluirlo) - 20% de los datos - validación y pruebas
entrenamiento_dataset = df[:idx_split, :] # Se toman los valores del índice para atrás - 80% de los datos - entrenamiento

# Se separa val_set de tal manera que podamos tener datasets tanto para validación como para pruebas
val_idx_split = int(val_set.shape[0] * 0.5) # 0.5 para obtener la mitad de los datos para validación y la otra mitad para pruebas

val_dataset = val_set[:val_idx_split, :] # Dataset de validación
pruebas_dataset = val_set[val_idx_split:, :] # Dataset de pruebas

### Análisis Exploratorio de Datos

In [29]:
# Calculando la media del dataset
media = np.nanmean(df, axis=0)
print(f"La media del dataset es:\n{media}\n")
# Calculando el valor máximo
max_val = np.nanmax(df, axis=0)
print(f"El valor máximo de cada variable del dataset es:\n{max_val}\n")
# Calculando el valor mínimo
min_val = np.nanmin(df, axis=0)
print(f"El valor mínimo de cada variable del dataset es:\n{min_val}\n")
# Calculando el rango
rango_val = max_val - min_val
print(f"El rango de cada variable del dataset es:\n{rango_val}\n")
# Calculando la desviación estándar
desv_val = np.nanstd(df, axis=0)
print(f"La desviación estándar de cada variable del dataset es:\n{desv_val}\n")

La media del dataset es:
[1.80921196e+05 6.09931507e+00 1.16262671e+03 6.51780822e+00
 1.97126781e+03 7.00499584e+01]

El valor máximo de cada variable del dataset es:
[7.550e+05 1.000e+01 4.692e+03 1.400e+01 2.010e+03 3.130e+02]

El valor mínimo de cada variable del dataset es:
[3.490e+04 1.000e+00 3.340e+02 2.000e+00 1.872e+03 2.100e+01]

El rango de cada variable del dataset es:
[7.201e+05 9.000e+00 4.358e+03 1.200e+01 1.380e+02 2.920e+02]

La desviación estándar de cada variable del dataset es:
[7.94152919e+04 1.38252284e+00 3.86455322e+02 1.62483655e+00
 3.01925588e+01 2.42746394e+01]



### Histograma para cada variable del dataset

In [ ]:
# Se itera sobre cada variable del dataset
for i in range(df.shape[1]):
    sns.distplot(df[:,i])
    plt.show()